### ISSUE TITLE
Support absolute path for extra theme

### ISSUE THREAD

**Issue by melck** [marp-team/marp-vscode#110]
I have tried this option "markdown.marp.themes" and like it is described, it only work with relative css file in workspace or url.

I want to have a external folder with multiple themes. Do you think u could support absolute path for that ?

**Comment by yhatt** [comment]
Our resolution rule is following as same as VS Code's `markdown.styles` rule. Unfortunately we have not thought absolute path support for `markdown.marp.themes` because there is potential security risk by a malicious workspace.

Refer to https://github.com/microsoft/vscode/issues/45260#issuecomment-371428889.

**Comment by melck** [comment]
Thanks for information :cry:. I understand why, but it's not really simple for external theme with image, etc.

**Comment by yhatt** [comment]
Sometimes we have to take an inconvenience for users safe. 😗

You can take some workarounds:

- Use symbolic link to global theme CSS folder (https://github.com/microsoft/vscode/issues/45260#issuecomment-385917347)
- Specify URL to served CSS in localhost through external tool (e.g. `http://localhost:3000/your-theme.css`)
- Use [Marp CLI](https://github.com/marp-team/marp-cli) (Perhaps some convertions requires insecure `--allow-local-files` flag)
