### ISSUE TITLE
enhancement: layout adjust

### ISSUE THREAD

**Issue by fastfading** [marp-team/marp-vscode#113]
although the fisrt markdown code line is aligned, however
keep left markdown code and preview ppt at the same level position as pic shows
 
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/8351732/71065899-21e5f980-21ad-11ea-8d72-464c96e26114.png">

this ui layout will be more comfortable.
you can see previous markdown code in this layout.

**Comment by yhatt** [comment]
Typically the active line may become vertically middle of preview pane. This behavior comes by following VS Code's scroll sync in Markdown preview.

We should not add extra scrolling behavior in the built-in preview pane becuase Marp for VS Code extension are responsible only for converting to Marp slide.

Please request to [microsoft/vscode](https://github.com/Microsoft/vscode) instead of here if you want an exact position tracking in Markdown preview.
