### ISSUE TITLE
PlantUML direct image integration for codeblock 'plantuml'

### ISSUE THREAD

**Issue by volodink** [marp-team/marp-vscode#131]
Now i can write this
```javascript
var s = "JavaScript syntax highlighting";
alert(s);
```
```python
s = "Python syntax highlighting"
print s
```
and i got nice hightlighted code.

Using this
![height:100%](http://www.plantuml.com/plantuml/svg/0/SoWkIImgAStDuNBAJrBGZLOkIas9jLDmpCbCJbMmKiX8pSd9vuBmW986GE3c5gjh1r9ifP2VpUMGcfS2r0q0)
i can add image to the slide.

Please, consider PlantUML image instead of codeblock highlighting, like
```plantuml
@startuml
a -> b
@enduml
```

**Comment by volodink** [comment]
Slide text:
---
# PlantUML vector chart test

```plantuml
@startuml
a -> b
@enduml
```

![height:100%](http://www.plantuml.com/plantuml/svg/0/SoWkIImgAStDuNBAJrBGZLOkIas9jLDmpCbCJbMmKiX8pSd9vuBmW986GE3c5gjh1r9ifP2VpUMGcfS2r0q0)

Preview image has no image, only highlighted text:
![изображение](https://user-images.githubusercontent.com/1587327/78499007-b40f0f00-7756-11ea-9b14-57b34e188293.png)

Turned off MARP preview has transformed image:
![изображение](https://user-images.githubusercontent.com/1587327/78499020-d0ab4700-7756-11ea-813a-f83f46dc4b70.png)

**Comment by yhatt** [comment]
*See essentially duplicate issue marp-team/marp-vscode#116.* [Community is giving an idea](https://github.com/marp-team/marp-core/issues/112) of using [markdown-it-plantuml](https://www.npmjs.com/package/markdown-it-plantuml) plugin in [Marp CLI](https://github.com/marp-team/marp-cli).

---

FYI, PlantUML image generation is not implemented to Marp for VS Code and all of our official tools because it requires extra PlantUML server working *in the out of JS world*. And we also have no plan to support PlantUML in official.

In your VS Code, probably [a generated image has provided by PlantUML extension](https://github.com/qjebbs/vscode-plantuml#markdown-integrating) when Marp preview was disabled. Marp will switch render engine to Marp *for getting consistent result in all of Marp tools*, so the other VS Code extensions for Markdown won't work.

**Comment by volodink** [comment]
> 
> 
> _See essentially duplicate issue #116._ [Community is giving an idea](https://github.com/marp-team/marp-core/issues/112) of using [markdown-it-plantuml](https://www.npmjs.com/package/markdown-it-plantuml) plugin in [Marp CLI](https://github.com/marp-team/marp-cli).
> 
> FYI, PlantUML image generation is not implemented to Marp for VS Code and all of our official tools because it requires extra PlantUML server working _in the out of JS world_. And we also have no plan to support PlantUML in official.
> 
> In your VS Code, probably [a generated image has provided by PlantUML extension](https://github.com/qjebbs/vscode-plantuml#markdown-integrating) when Marp preview was disabled. Marp will switch render engine to Marp _for getting consistent result in all of Marp tools_, so the other VS Code extensions for Markdown won't work.

Thanks for explanation. Is there any documentation on how to do https://github.com/marp-team/marp-vscode/issues/116#issuecomment-571024416 
Where should i place marp.config.js ?

**Comment by yhatt** [comment]
It have to use Marp CLI so see also [Marp CLI documentation](https://github.com/marp-team/marp-cli#readme). [Functional engine](https://github.com/marp-team/marp-cli#functional-engine) will be helpful.

NOTE: Marp for VS Code does not support custom Marp CLI config. Our community is working in #123 for VS Code integration.
