### ISSUE TITLE
CLIError when exporting to PDF: dir option must be relative to "/tmp"

### ISSUE THREAD

**Issue by fdegrave** [marp-team/marp-vscode#166]
Hi,

When I try to export my file to PDF I get the following error:

> Failure to export: [CLIError] Failed converting Markdown. (dir option must be relative to "/tmp", found "/home/fd".)

I tried playing around with the few settings available but no luck. Any chance you can help me?

Cheers,

François

**Comment by yhatt** [comment]
It will be resolved by merging the latest Marp CLI v0.21.1: https://github.com/marp-team/marp-cli/issues/201, https://github.com/marp-team/marp-cli/pull/283, #165 

But Marp CLI in the same VS Code environment still reported another issue (https://github.com/marp-team/marp-cli/issues/287). We will merge and release new version of the extension as soon as fixed it.

**Comment by yhatt** [comment]
A reported error has been fixed by updating Marp CLI. Try new release of the extension, v0.15.1.

If you may see another error message like "Puppeteer was unable to kill the process...", try these steps:

1. Open VS Code setting.
2. Find out `Markdown > Marp: Chrome Path`, and set "`/snap/chromium/current/usr/lib/chromium-browser/chrome`".
3. Restart VS Code.
4. Try again export to PDF.

**Comment by arjunskumar** [comment]
`Failure to export: [CLIError] Failed converting Markdown. (kill EACCES) ` occurs whenever i try to save into pdf, i can now save as html
