### ISSUE TITLE
Method to easily implement figure floating in Marp

### ISSUE THREAD

**Issue by YutaroIshihama** [marp-team/marp-vscode#172]
I would like to make figures movable by wrapping texts easily. Because of my deficiency in css knowledge, I almost always use table environment to implement this... It would be very helpful if I could know a way to implement this, for example, by declaring in the header part of Marp, i.e., around the declaration `marp: true`. After my browser search, I reached the result in the case of usual html that a css file should be accompanied with the main html file. This css code should be like:

```
img {
  float: right;
}
```
If this code is also effective to the Marp system, I think I should prepare a css file likewise and save it in the same directory with the main markdown file. In my guess, this is not true in the case of Marp. I would also like to avoid html mode in Marp (i.e., --html) because I have no idea how to implement this in the mode of Marp-Vscode. Thanks in advance for your help...

**Comment by yhatt** [comment]
> :warning: Please keep in mind the issue tracker of this repository is for tracking the extension's bug and ideas, not the support forum for Marp user. [Read support guideline](https://github.com/marp-team/.github/blob/master/SUPPORT.md#question) before creating an issue.

To layout contents as you like, you must learn CSS because Marp is based on Web basics, HTML and CSS. Marp Markdown can use [`<style>` html tag](https://marpit.marp.app/theme-css?id=tweak-style-through-markdown) to apply CSS even if not enabled HTML.

If you want to use `float`, you have to know that `float` would not work on many built-in Marp themes because [floats do not intrude into the flex container](https://www.w3.org/TR/css-flexbox-1/#flex-containers) and [a lot of themes have auto vertical centering with flex container](https://github.com/marp-team/marp-core/search?q=flex). You have to accept trade-off of disabled centering with using extra CSS such as `section { display: block; }`.
