### ISSUE TITLE
Failed to export local image when using gaia theme

### ISSUE THREAD

**Issue by AseiSugiyama** [marp-team/marp-vscode#175]
When I export the following markdown with marp-vscode, 

```markdown
---
marp: true
theme: gaia
inlineSVG: true
---

<!-- _class: lead -->
# Sample Slide

---

# Sample Slide

![bg right fit](plate.jpg)
```

the result is this.

![image](https://user-images.githubusercontent.com/30427632/96137014-0f586000-0f37-11eb-820d-0a55bc537375.png)

However, when I used default theme (drop the `theme: gaia` line), marp for VSCode exports local image correctly.

![image](https://user-images.githubusercontent.com/30427632/96137296-76761480-0f37-11eb-9f43-393c7323a58f.png)

Sample markdown and image are here. https://github.com/AseiSugiyama/marp_test

I guess this issue is not caused by https://github.com/marp-team/marp-vscode/issues/134 , so I opened this new issue.

**Comment by yhatt** [comment]
We've confirmed reproducibility. Start finding out the root cause.

Probably marp-team/marp-cli#293 is pointing out a similar problem.

> *NOTE: `inlineSVG` is the constructer option for developer, not global directive for Marp / Marpit. Defining `inlineSVG: true` in front-matter is no meaning because our Marp Core is always enabling inline SVG mode.*

**Comment by yhatt** [comment]
I'm guessing this bug comes from Chrome/Chromium. Marp internally converts HTML into PDF through installed Chrome.

I've confirmed there is often a broken [advanced background image for inline SVG mode](https://marpit.marp.app/image-syntax?id=advanced-backgrounds) if printed the exported HTML to PDF through Chrome >= 85. It happens _in any theme_, not limited to gaia theme.

- Chrome 86 (Chromium r800071: latest): :x:
- Chrome 85 (Chromium r782078): :x:
- Chrome 84 (Chromium r768783): :white_check_mark:

I'll continue working for finding out the workaround.

**Comment by AseiSugiyama** [comment]
Thank you for your great work! I was able to make my work finished by exporting my slide as a HTML file and print it out as an PDF file. I'm very glad if my example files help to find the root cause of this issue.

**Comment by yhatt** [comment]
Reporting details to Chromium bug tracker helps to resolve the root cause.
https://bugs.chromium.org/p/chromium/issues

I found out the exported HTML in Marp CLI with [bare template](https://github.com/marp-team/marp-cli#bare-template) can render background images correctly. We were supposed to have designed the default template ([`bespoke`](https://github.com/marp-team/marp-cli#bespoke-template-default)) also can convert to PDF, but probably injected scripts to control presentation might be prevented some background image rendering since Chrome 85.

We will implement to Marp CLI the fallback of using bare templatewhen running Chromium-based conversion.

**Comment by Sahuta** [comment]
Hi
This issue is seemed to still exists, when background images placed right and vertically, when exported as .pdf or .pptx as I checked. When HTML, it goes well. I use default theme, overwriting only fonts to Noto Sans JP by css.

**Comment by yhatt** [comment]
@Sahuta Which version of VS Code, Marp extension, and Chrome browser (including Canary) are you using?

**Comment by Sahuta** [comment]
Code 1.60.1
Chrome 91.0.4472.164
￼
Sorry for late!

**Comment by yhatt** [comment]
@Sahuta We have not yet recieved any trouble reports about in your environments. I guess the root cause is different from this issue.

### Trobuleshootings

- Update Chrome to the latest version v93.
- Set the executable path of Chrome in the extension setting, and try to export again.
- When you're using Windows, check if you are not using an invalid path delimiter for the image path. Should use `/` instead of `\` because URL only allows `/`. (#143)
- If you are using images through remote URL, please confirm your network status as online when exporting. When required proxy, check the system setting about proxy.
- Check whether it reproduces when all extensions excluded Marp have disabled.
- If you're using Marp extension over a remote container or a remote repository (e.g. SSH, WSL, Docker, Live Share session, GitHub Repositories extension), [Marp for VS Code may not read image files from a virtual workspace correctly.](https://marp.app/blog/marp-for-vs-code-v1#virtual-workspace-support-) Please report about combinated extensions with Marp.
- If still failed, please create a new issue and share the log of the export command, that is shown in the console of VS Code developer tools. (`Help` -> `Show Devloper Tools` -> `Console` tab)

**Comment by Sahuta** [comment]
So sorry I’ve set image URL using backslash  only where I using vertical alignment. 
After fixed to /, they went good. Thanks for developing this app great choice for slides with beautiful equation.
