### ISSUE TITLE
[Marketplace] Provide VSIX on Github

### ISSUE THREAD

**Issue by ulfgebhardt** [marp-team/marp-vscode#182]
## Problem

Navigating to the [Marketplace](https://marketplace.visualstudio.com/items?itemName=marp-team.marp-vscode) and trying to [download the Extension](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/marp-team/vsextensions/marp-vscode/0.16.0/vspackage) from there results in:

```
{
$id: "1",
innerException: null,
message: "Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic "Rate limits" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).",
typeName: "Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server",
typeKey: "RequestBlockedException",
errorCode: 0,
eventId: 3000
}
```

## Solution
Please provide the VSIX with your Release on Github, so you can download it from there.

Alternative advise the user to accept cookies from the marketplace in order to download the stuff from the marketplace page

**Comment by yhatt** [comment]
Commonly the error from Visual Studio Marketplace is only temporal caused by Microsoft's [global rate limit](https://go.microsoft.com/fwlink/?LinkId=823950). _VS Code user can install Marp extension from VS Code app directly so probably we would not work to resolve your problem if you are using VS Code._

Nevertheless, bulding up automated release process may be good for GitHub releases and in-future publishing into [Open VSX](https://open-vsx.org/). We will work for that if you are using [VSCodium](https://vscodium.com/).

### Details

VSCodium user (#169)  cannot use downloaded VSIX from VS Marketplace due to terms of service. In short, using downloaded VSIX from Marketplace for other than VS Code may be **possibly illegal**. (https://github.com/VSCodium/vscodium/issues/418)

VSIX on GitHub releases (or Open VSX) would be able to provide a way for bypassing illegal usage of extension.

**Comment by ulfgebhardt** [comment]
Check out this repo - they have a VSIX in their release: https://github.com/tomoki1207/vscode-pdfviewer/releases/tag/v1.0.0

**Comment by yhatt** [comment]
Whether the other extension is doing does not very matter. We have importance to the worth for many users rather than a workaround for a one user.
