### ISSUE TITLE
PDF export with custome theme not working properly in 1.4.1, 1.4.2 and 1.4.3

### ISSUE THREAD

**Issue by sgudenkauf** [marp-team/marp-vscode#305]
### Version of Marp Tool

Marp for VS Code v1.4.3

### Operating System

Windows

### Environment

- Windows 10 Enterprise, 21H1
- Marp for VS Code v1.4.3
- Visual Studio Code 1.60.2 

### How to reproduce

1. My custom css theme resides in a local subfolder `./css` and is added via the global directive `theme`.
2. The css theme's `@theme` metadata ist set correctly.
3. The Markdown file additionally contains scoped inline styles.

### Example: 

file.md
```
---
marp: true
theme: test  
---

<style scoped>header, footer {color: #fff; } section { justify-content: center;}</style>

# Title
Text
```

test.css
```
/* @theme test */

@import 'default';

h1 { 
    font-family: Rockwell,Courier Bold,Courier,Georgia,Times,Times New Roman,serif; 
    font-size: 3em; 
    font-style: normal; 
    font-variant: normal; 
    font-weight: 700; 
    color: #f22e62; /*f22e62*/ /*ff4733*/
} 
```

### Expected behavior

The theme is applied to PDF export.

### Actual behavior

The theme is used in VS Code Preview but not applied to PDF export.
- Switching to 1.4.2 and 1.4.1 shows the same behavior.
- Switching to 1.4.0 is fine though and does not show the observed behavior.

### Additional information

Of course, I may well be using the program incorrectly. In any case, thank you very much for your work!
Stefan

**Comment by yhatt** [comment]
I have tried to reproduce the bug with your codes that have located to the local file system, but still could not reproduce this bug on Marp v1.4.3 and VS Code 1.60.2.

![](https://user-images.githubusercontent.com/3993388/136982871-a0630f02-80b0-4c9a-a103-0d689e253ded.png)

Try to reinstall the latest extension without implicit caches.

1. Remove Marp extension from VS Code.
2. Close VS Code.
3. Open "C:\Users\your-name\.vscode\extensions" in explorer.
4. Remove cached Marp extensions such as `marp-team.marp-vscode-1.4.x` if existed.
5. Reopen VS Code and install the latest Marp extension.

If still not working, please share more details:

- Logs outputted to the developer console when running export command (`Help` -> `Toggle Developer Tools` -> `Console` tab)
- Is your project has located to the remote instead of local filesystem? (e.g. WSL, SSH, Docker, Live share session, Remote repository, etc)

**Comment by yhatt** [comment]
Close for housekeeping due to outdated. Please share more info if you are not yet resolved.
