### ISSUE TITLE
Not possible to export in remote container

### ISSUE THREAD

**Issue by zioalex** [marp-team/marp-vscode#310]
### Version of Marp Tool

0.19.1

### Operating System

Windows

### Environment

- OS version: Windows 10 x64 10.0.19042 with an Ubuntu Focal  remote container OS 
- Node.js version v12.18.3
- VS Code version 1.53.1

### How to reproduce

1. Start VScode 
2. Connect to the remote container
3. Open a MD presentation file
4. Issue the Marp export command
5. select the destination folder

### Expected behavior

The type of export ( Pdf, Html, PPT) is requested and the relative exported presentation will be created.

### Actual behavior

I got the follow error:
![image](https://user-images.githubusercontent.com/3593840/141077134-f973ed28-aba9-45d8-97ac-78b29a0f0d81.png)

### Additional information

I didn't find any way to get additional information.
The rendering inside VScode works properly.

I've installed chrome from the standard Ubuntu repo and now google-chrome binary is available in /usr/bin.

**Comment by yhatt** [comment]
You're using the outdated VS Code and Marp extension. The latest version is VS Code v1.62.2 / Marp for VS Code v1.4.3. Try again with the latest version.

**Comment by yhatt** [comment]
Close for housekeeping. If still not worked in suggested versions, please share the behavior in the latest version.

**Comment by zioalex** [comment]
Hi @yhatt thanks for the suggestion.
Now with the latest versions I can export the presentation but I cannot select anymore the output format.
When I select the export function, I have to specify a path for the export and then it will happen.
Dependently from the file extension (.pdf, .html, .pptx) the file will be exported accordingly, but I remember a different flow with the previous version where I had to explicitly choose the export format.

Is anything changed?

**Comment by yhatt** [comment]
marp-team/marp#148 has reported that some Linux distributions would not add the file extension automatically when exporting. It had brought user's confusion by the output with unexpected file type. Since v1.3.0, the default filename in the file picker has added a default extension like ".pdf" to deal with that.

To change the export type in the file picker for remote container, please rename the extension in a filename. You also can set the default export type from Marp's setting (`markdown.marp.exportType`).
