### ISSUE TITLE
:first-child doesn't work in theme

### ISSUE THREAD

**Issue by dreampuf** [marp-team/marp-vscode#328]
### Version of Marp Tool

Marp for VS Code v1.4.7

### Operating System

macOS

### Environment

- OS version: macOS Monterey 12.1
- Node.js version (Marpit / Marp Core/ Marp CLI): Node.js: 14.16.0
- VS Code version (Marp for VS Code): VS Code 1.64.0

### How to reproduce

```markdown
---
marp: true
style: |
  @import 'default';
  section:first-child {
      color: red;
  }
  
  section {
      color: black;
  }
---
<!-- headingDivider: 2 -->

# Theme test

to test marp

# Slide 2

page 2
```

<img width="583" alt="image" src="https://user-images.githubusercontent.com/353644/153820420-34057de1-6a4b-4c84-a159-91db85053e00.png">

### Expected behavior

The text should be black in the second slide.

### Actual behavior

Both two slides have red text.

**Comment by yhatt** [comment]
Not working `:first-child` pseudo selector is _as designed_ because a Marp slide that may render in various ways in many tools like CLI and third-party tools (e.g. [Marp for Standard Notes](https://github.com/TheodoreChu/marp-editor)) should not have dependency to the parent element in a specific tool.

If you want page-number based narrowing in global style, consider to use a page number anchor ID instead of `:first-child`.

```css
section[id="1"] {
  ...
}
```

> Note: `section#1` will not work. Require non-intutive escape like `section#\31`.

**Comment by dreampuf** [comment]
Hi @yhatt Thank you for the great tool. I didn't find this part in the [document](https://marpit.marp.app/theme-css). Where can I find these information?

**Comment by yhatt** [comment]
@dreampuf There is no documentation anywhere because _Marp team does not recommend this way to set the style_. Using `id` is currently working but it would not be consistently working in the future (We have a plan to allow changing the format of `id` to Marp developers).

It would be better to use [scoped style](https://marpit.marp.app/theme-css?id=scoped-style) or [`class` directive](https://marpit.marp.app/directives?id=class) to the first slide.

**Comment by dreampuf** [comment]
@yhatt I don't want to specify the style on a random page but I do want a formal style of the first page and maybe the last one. The extra mark works for me. It would be great that if marp could provides a buit-in set of class to mark which page you are in. Thanks.
