### ISSUE TITLE
Open Preview to the Side button desapeared.

### ISSUE THREAD

**Issue by cunhapaulo** [marp-team/marp-vscode#336]
I was wondering weather this was only happening to me.
I use MARP in VS Code and all of a sudden the `Open Preview to the Side` button desapeared. Just like in the picture below:

![image](https://user-images.githubusercontent.com/28146759/160387098-12840130-e4f4-44f3-b517-3581258967c3.png)

Any ideas about?

Thanks in advance!

**Comment by yhatt** [comment]
_Transferred issue from marp-cli repository to marp-vscode._ 🚚 

Other extensions that have been installed together with Marp for VS Code may make an adverse effect.

For example, [Markdown Preview Enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/), that is one of very popular Markdown extension in VS Code, will hijack and hide VS Code's `Open Preview to the Side` button. If MPE extension had been installed into your VS Code, try to disable the extension, or turn off `markdown-preview-enhanced.hideDefaultVSCodeMarkdownPreviewButtons` in settings.

![](https://user-images.githubusercontent.com/3993388/160412204-e80263cd-3253-408c-ad78-a364ccdd4357.png)

Require to restart VS Code after changing the state.

> MPE can write and preview presentation in Markdown but does not support Marp, and also not provide the contribution point to extend Marp support.
>
> - Related issue: https://github.com/shd101wyy/markdown-preview-enhanced/issues/1253

Of course, the other extension also might make the button hide. If necessary, you can find out the extension that brings a root cause by using [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect).

**Comment by cunhapaulo** [comment]
Most certainly this is the cause!
Thank you very much for your perfect explanation!
