### ISSUE TITLE
Cannot detect simplified URLs 

### ISSUE THREAD

**Issue by BSeyfi** [marp-team/marp-vscode#368]
### Version of Marp Tool

Marp for VS Code v2.1.0

### Operating System

Windows

### Environment

- OS version: Windows 7
- Marp for VS Code v2.1.0

### How to reproduce

First, I thank you very much for the MARP.
And the bug:
When I put a simplified url in the `footer` directive (like github.com/bseyfi ), Marp couldn't recognize it as a url. ( complete form of url is OK (like https://github.com/bseyfi ))
This bug was not present in earlier version (1.5).
I've detected this bug by changing the color of url by css directive:

```css
<section>
a:link {
color: blue;
}
</section>
```

Thanks in advance

### Expected behavior

I expect the simplified version of URL is recognized by Marp

### Actual behavior

Treats the simplified version of a url like a regular text and not as a url.

**Comment by yhatt** [comment]
This is an as-desgined behavior in Marp Core v3, not a bug. Refer to https://marp.app/blog/202205-ecosystem-update#url-without-https-scheme-does-no-longer-auto-linkify.

The latest Marp Core requires explicit hyperlink syntax `[github.com/bseyfi](https://github.com/bseyfi)` to simplified URL because we have received feedback some of users were in trouble with too fuzzy auto link (Amazon.com, ASP.NET, ML.net, etc).

```markdown
---
header: "[github.com/bseyfi](https://github.com/bseyfi)"
---
```
