### ISSUE TITLE
Failure to export: [CLIError] Failed converting Markdown. (kill EACCES)

### ISSUE THREAD

**Issue by twitu** [marp-team/marp-vscode#369]
Ubuntu 20.04
VS Code 1.69.2
Extension version 2.1.0

It fails to export a PDF. The markdown presentation is pretty basic, no fancy markup used.

I've tried setting chromePath as well based on previous issues.

A point to note is that both vscode and chromium are installed using snap.

**Comment by yhatt** [comment]
> A point to note is that both vscode and chromium are installed using snap.

We've known PDF export will not work if both VS Code and Chromium are installed through snap. If either of them was installed through Debian package, PDF export should work straightly.

- marp-team/marp-cli#287
  - [Workaround](https://github.com/marp-team/marp-cli/issues/287#issuecomment-693500881) (insecure)
- https://github.com/marp-team/marp-vscode/blob/c4c131cac228ee70f4ba73ae5fbd2c701a5788df/CHANGELOG.md?plain=1#L372

### snapd

- https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1849753
- https://github.com/snapcore/snapd/pull/10029
  - This problem should be fixed by this pull request to snapd. But unfortunately, it seems to have been delayed to work on that. If you want to stick to snap apps, it might be good to raise your voice to snapcraft community.

**Comment by twitu** [comment]
I've used the marp-cli to workaround this issue.

**Comment by alexmurray** [comment]
Since the `code` (VS Code) snap is classic, it could avoid this issue by ensuring it runs as `unconfined` as is done by say the `emacs` snap to avoid such issues:

https://github.com/alexmurray/emacs-snap/blob/master/setup-env#L46
