### ISSUE TITLE
use of firefox to export in pdf

### ISSUE THREAD

**Issue by Nuliel** [marp-team/marp-vscode#370]
Hello,
My question is simple: is it possible to use firefox instead of edge/chrome/chromium to export in pdf? I've not found an answer to my question so I create an issue. In fact I don't want to install a browser just to export in pdf.
I've tried to set chrome path to the path of firefox but the process never ends, and I also tried to pass "/usr/bin/firefox -headless" but it also doesn't work. 
Why a browser is needed to export in pdf? Is it exported in html and then converted to pdf by the browser? Is it possible to replace the browser with pandoc or an alternative?
Sincerely,
Nuliel

**Comment by yhatt** [comment]
No, you cannot use Firefox to export into PDF. The headless Firefox does not support PDF output from HTML unlike Chromium-flavored browsers.
https://bugzilla.mozilla.org/show_bug.cgi?id=1407238

> Why a browser is needed to export in pdf? Is it exported in html and then converted to pdf by the browser?

That's right. Marp is just a converter from Markdown+theme CSS to HTML, and slide rendering relies on the browser. The PDF conversion is doing Markdown -> HTML (via [Marp Core](https://github.com/marp-team/marp-core) and HTML -> PDF (via Chromium) at once.


Using the browser to generate PDF is a standard way in recent slide frameworks based on Web technologies also including Marp, because of HTML/CSS/JavaScript requirements for the modern specifications. If used a non browser tool as alternative, getting PDF with the exactly same rendering result as a preview would become difficult due to lacked .


FYI [Marp CLI's Docker container image](https://hub.docker.com/r/marpteam/marp-cli/) is [exactly designed for users who hates to install Chrome](https://github.com/marp-team/marp-cli#:~:text=Don%27t%20you%20like%20installing%20Node.js%20and%20Chrome%20to%20local%3F%20We%20have%20an%20official%20Docker%20image%20marpteam/marp%2Dcli%20ready%20to%20use%20CLI.).

**Comment by Nuliel** [comment]
Ok, thank you for your detailed answer. I will use the docker image.

**Comment by yhatt** [comment]
**UPDATE**: Marp for VS Code v3.0.0 has been supported exporting by using Firefox. :fox_face:

**Comment by xtremearts** [comment]
Can you detail more about Marp in Firefox?

**Comment by yhatt** [comment]
@xtremearts When Marp is necessary to use the browser internally to run export command, Marp will find out the already installed browser automatically from Chrome, Edge, and Firefox.

Up to Marp for VS Code v2, automatic detection was only supported in Chrome and Edge. Firefox support has been added from v3. Firefox users basically should not need extra actions.

For backward compatibility, Marp prefers Chrome than Firefox in auto detection. If you've installed both browsers, you may set `markdown.marp.browser` option as `firefox` explicitly to run export command with Firefox.
