### ISSUE TITLE
Failure to export

### ISSUE THREAD

**Issue by cviroulaud** [marp-team/marp-vscode#377]
Hello
I try marp (2.2.1) in vscodium (1.70.1) but i have an error when exporting:

[CLIError] Failed converting Markdown (protocol error (Target.setAutoAttach): target closed)

Chromium is installed

Thank you

**Comment by cviroulaud** [comment]
Debian 11
Vscodium 1.70.1
Marp for vscode 2.2.1
Chromium 104 (path /etc/chromium)

I try this code:
`
---
marp: true
---

# Slide 1

foo

---

# Slide 2

bar
`

then Marp: Export Slide Deck
---> [CLIError] Failed converting Markdown (protocol error (Target.setAutoAttach): target closed)

**Comment by yhatt** [comment]
That error will be happen if failed spawning the process of Chromium browser. The path `/etc/chromium` you've described is likely a wrong path because generally _it's a folder, not executable_.

If you have a path in manually set in `markdown.marp.chromePath`, please reset it to the empty and retry, to leave the browser detection to Marp. I've tested PDF export in VSCodium on Debian and it works for me.

**Comment by cviroulaud** [comment]
I change the chromium 's package and it works
thanks
