### ISSUE TITLE
Math blocks don't scale

### ISSUE THREAD

**Issue by tosaba** [marp-team/marp-vscode#38]
For the current version, equations are not scaled anymore to fit the size of the slide. Probably this issue is related to marp-core functionality, but for me, this appears within vs-code.
In the [documentation](https://github.com/marp-team/marp-core) of marp-core, it's written that the auto-scaling does not work with the uncover-theme. I am using `theme: default`.
It does not matter whether any `[bg right]` image is included on the slide or not.

Thanks!

``` markdown
# Some title

Eq. that fits into one line (no block) 
$S_1 = C_0 + n S_3$


Eq. that doesn't fit into one line (block)
$$S_1-S_3 = C_0 + \left(1-n\right)P_p - \left(1-n\right)S_3$$

Eq. that doesn't fit into one line (no block)
$S_1-S_3 = C_0 + \left(1-n\right)P_p - \left(1-n\right)S_3$

![bg right](test.png)

```

![image](https://user-images.githubusercontent.com/17127576/57684893-feffcf80-7636-11e9-995c-fdeca17ee48c.png)

**Comment by yhatt** [comment]
As same as #8, it would be caused by a rendering bug in the old Chromium version in VS Code (Electron 3.x / Chrome 66). It displays correctly on VS Code for exploration (based on Electron 4.x / Chrome 69: https://github.com/microsoft/vscode/issues/61787).

![Diffrence between Electron 3 and 4](https://user-images.githubusercontent.com/3993388/57688287-0abfb600-7678-11e9-92a8-7a45f2158f2b.png)

Waiting to update of VS Code is the only thing that we can do, but unfortunelly an update to Electron 4 is still blocked (https://github.com/microsoft/vscode/issues/61787#issuecomment-473240877).

For a while, use Marp CLI's preview mode as a workaround.

```
npx @marp-team/marp-cli --preview your-markdown.md
```

**Comment by yhatt** [comment]
Now [VS Code 1.36-insider](https://code.visualstudio.com/insiders/) is using Electron 4. It would resolve scaling issue. (But there is another issue: #45)

**Comment by yhatt** [comment]
Now VS Code v1.36 reaches to stable.
