### ISSUE TITLE
embed  pdf through iframe, but the embed pdf is fuzzy 

### ISSUE THREAD

**Issue by hanqing0521** [marp-team/marp-vscode#383]
I want to embed a pdf in my representation. The iframe of html tag was used 
```
<iframe width="100%" height="80%" src="PhysRevB.67.085311.pdf" frameborder="0">
</iframe>
```
Not only the `marp-vscode` but also the `marp-cli`  generates the html with  fuzzy embedded pdf 
[![xiWEZQ.png](https://s1.ax1x.com/2022/09/21/xiWEZQ.png)](https://imgse.com/i/xiWEZQ)

when disable marp and exporting html by `Markdown PDF` in VSCode , it works well.
May some one give me some support. Thanks

**Comment by yhatt** [comment]
PDF within `<iframe>` is rasterized based on the original slide page size (1280x720), and the browser shows the enlarged slide to fit to the screen.

If you were using a screen larger than actual page size, PDF may be obscure due to insufficient renderd pixels.

- Define and use [the custom theme CSS](https://marpit.marp.app/theme-css), that has [the same or larger slide size](https://marpit.marp.app/theme-css?id=slide-size) than the actual display size.
- In Chrome/Chromium, try to force x2 and upper rendering scale factor through `--force-device-scale-factor=2` command line option.
- Use an alternative browser that has better upscaling render, such as Firefox.

**Comment by yhatt** [comment]
Marp has a correct behavior about making slide in reality, so we would not take any action for this.

**Comment by hanqing0521** [comment]
Thanks, and is there any better method for embedding pdfs?
