### ISSUE TITLE
Cannot set custom theme css: The specified theme " " is not recognized by Marp for VS Code. marp-vscode(unknown theme)

### ISSUE THREAD

**Issue by BRPolaris** [marp-team/marp-vscode#403]
Hello. 

I follow the guide to make my own custom theme css, but I failed.
I follow all the steps of the guidance,  make a settings.json and put it in the "/.vocode"  of my workspace, then make the theme css and put it in the "/themes" of my workspace, but when I open a md and set the theme I made, it shows the alarm 'The specified theme " " is not recognized by Marp for VS Code. marp-vscode(unknown theme)'.

I don't  know why and  look forward to your help， 
Many thanks！

**Comment by yhatt** [comment]
We cannot guess what happening to you because of there are less informations Please share more context around at the [Marp discussion forum](https://github.com/orgs/marp-team/discussions) to get answer. (e.g. the actual contents of Markdown, theme CSS, and `.vscode/settings.json`. [The issue tracker in each Marp GitHub repositories are not designed to ask for support](https://github.com/marp-team/.github/blob/master/SUPPORT.md#how-about-github-issues))

> FYI the alert you've reported may be bringing by setting theme name as a white space `" "` in your Markdown. Instead, you have to specify the name of your custom theme `xxxxx` named by `/* @theme xxxxxx */` comment.
> 
> ```markdown
> ---
> marp: true
> theme: " "
> ---
> ```
