### ISSUE TITLE
Image does not get generated in exported pdf file

### ISSUE THREAD

**Issue by georgikoemdzhiev** [marp-team/marp-vscode#404]
I have a local png image that I have put onto my slide using the following code:

```markdown
---
theme: gaia
_class: lead
paginate: true
backgroundColor: #fff
marp: true
backgroundImage: url('https://marp.app/assets/hero-background.svg')
---

## Long-term approach proposal

Convert existing terraform infra into modules with parameters.
![](/assets/images/combined2.png)
```

The image renders fine in the preview window in VS:
![image](https://user-images.githubusercontent.com/11027608/217529140-922d7f9f-3eba-41ee-be00-4256e12ec22b.png)

However, when I export my desk using `mark: Export my Slide Deck` command, the slide I get in the `pdf` file does not have the image:
![image](https://user-images.githubusercontent.com/11027608/217529395-cfeba852-3703-417f-80b3-8b385fd0a224.png)

Here is the image I am using:
![combined2](https://user-images.githubusercontent.com/11027608/217529033-96abca3d-c1e5-4315-aa41-7fbebcfcf1a2.png)

**Comment by yhatt** [comment]
> 🚚 Transfered issue from Marpit framework to Marp for VS Code.

In VS Code preview, any resources which were specified in the absolute path will have a different resolution way from other Marp tools, due to the specifcation of the Markdown preview. (The export command also can regard as one of other tools because it's actually using Marp CLI in internal)

In common, `![](/assets/images/combined2.png)` has an exactly same meaning as `<img src="/assets/images/combined2.png" />`, and regularlly that path points out a local file resolved from the root: `file:///assets/images/combined2.png`

On the other hand, the root of resources used for VS Code Markdown preview will become the root of VS Code workspace you'are opening. If you were opening `/home/username/marp/markdown` directory as a VS Code workspace, the preview can show an image located in `/home/username/marp/markdown/assets/images/combined2.png` with the described absolute path.

## Solutions

### Use relative path

A thinking about "workspace" is VS Code specific. For interoperability with other Marp tools, we recommend to use a relative path from Markdown file instead.

```markdown
![](./assets/images/combined2.png)
```

### Experimental `markdown.marp.strictPathResolutionDuringExport` option

If you want to stick to use absolute path from the workspace root, you can try to export with turning on _an experimental_ **`markdown.marp.strictPathResolutionDuringExport`** setting from the extension preference too. It's useful for getting more consistent result between preview and export.

See details in #367.

> This is still an experimental feature so may have some unexpected behaviors. Welcome your feedbacks :)

**Comment by georgikoemdzhiev** [comment]
Thank you very much for explaining what the issue was. I never tried to experiment with the path. That fixed the issue :) 

Thank you for the awesome project! 🚀
