### ISSUE TITLE
Line numbers in the code block using Marp in VSC

### ISSUE THREAD

**Issue by icecloud-dcp** [marp-team/marp-vscode#413]
I tried to add the line numbers in the code block with Marp md. I tried to change theme and/or marp theme css settings. But it doesn't display the line number. Is Marp extension in VSC supported?

**Comment by yhatt** [comment]
The answers are all in https://github.com/marp-team/marp/discussions/164. In short, you always have to use Marp CLI instead of Marp for VS Code because it requires customization the Markdown conversion engine.

Marp has never supported the `line-numbers` directive officially, so you are probably trying to use some different Markdown flavor.
