### ISSUE TITLE
Unable to export in Flatpak VSCode

### ISSUE THREAD

**Issue by josecastillolema** [marp-team/marp-vscode#451]
Is there a way to export slides in the Flatpak version of VSCode?

I am able to run i.e.: Chrome from the Flatpak vscode version:
```
> flatpak run --command=sh com.visualstudio.code
[📦 com.visualstudio.code]$ flatpak-spawn --host flatpak run com.google.Chrome
```

However unfortunately the following setting does not seem to work:
```
"markdown.marp.chromePath": "flatpak-spawn --host flatpak run com.google.Chrome"
```

**Comment by yhatt** [comment]
`markdown.marp.chromePath` does not allow the shell command. You must specify the actual path for the Flatpak Chrome binary.

```json
{
  "markdown.marp.chromePath": "/var/lib/flatpak/app/com.google.Chrome/current/active/export/bin/com.google.Chrome"
}
```

**Comment by josecastillolema** [comment]
Hi @yhatt , thanks for your quick response!
Unfortunately that won't work, **/var/lib/flatpak** is not accessible from inside flatpaks (neither is **$HOME/.local/share/flatpak/exports/bin**):
```
> ls /var/lib/flatpak/exports/bin/com.google.Chrome
/var/lib/flatpak/exports/bin/com.google.Chrome

> ls .local/share/flatpak/exports/bin/com.google.Chrome
.local/share/flatpak/exports/bin/com.google.Chrome

> flatpak run --command=sh com.visualstudio.code
[📦 com.visualstudio.code ~]$ ls /var/lib/flatpak/exports/bin/com.google.Chrome
ls: cannot access '/var/lib/flatpak/exports/bin/com.google.Chrome': No such file or directory

[📦 com.visualstudio.code ~]$ ls .local/share/flatpak/exports/bin/com.google.Chrome
ls: cannot access '.local/share/flatpak/exports/bin/com.google.Chrome': No such file or directory
```

The proposed workaround would work if VSCode was not a Flatpak and Chrome was, but wont work when both of them are.

This is by design, see [ Allow a flatpak to discover/call another flatpak #283 ](https://github.com/flatpak/xdg-desktop-portal/issues/283)

**Comment by yhatt** [comment]
Thank you for more context to recognize the problem. By the design of flatpak as you've described, using flatpak Chrome from flatpak VS Code to export Marp slides would be difficult for now.

It looks like able to spawn Chrome process, by making the wrapper shell script like below and setting its path to `markdown.marp.chromePath`. But even if it succeed, the result of export PDF will save to inside of the Chrome flatpak sandbox, so _VS Code cannot read that across sandboxes._

<details>
<summary>The example of wrapper script (Click to open)</summary>

```sh
#!/bin/sh

flatpak-spawn --host /var/lib/flatpak/exports/bin/com.google.Chrome "$@"
```

</details>


If there were the SDK Extension of freedesktop.org for Chrome/Chromium, this problem may be solved because the browser will be available in inside of the VS Code flatpak sandbox. This is already feedbacked to the Flathub community through [Obsidian Marp Slides plugin](https://github.com/samuele-cozzi/obsidian-marp-slides), but there is no progress.

- [Packaging Chromium as an extension request](https://discourse.flathub.org/t/packaging-chromium-as-an-extension-request/4339)
- https://github.com/flathub/md.obsidian.Obsidian/issues/157

**Comment by josecastillolema** [comment]
The wrapper works!
And the result of the export PDF is not saved inside the Chrome flatpak, but in any directory inside the home folder selected by the user.

Thanks
