### ISSUE TITLE
Theme and Preview

### ISSUE THREAD

**Issue by LogicLord-Liu** [marp-team/marp-vscode#457]
Hello !

I encountered a few issues when using the Marp plugin in VSCode
* Why does using the marp theme and various styles have no effect in VSCode?
* And why is the real-time rendering not in the form of PPT but in the form of PDF?
* Why is this the case ?

**Comment by yhatt** [comment]
We need more information about the context in which you are using Marp for VS Code. For getting more accurate answers, please provide [the minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). You can also use [GitHub Discussions](https://github.com/orgs/marp-team/discussions) when asking anything about Marp.

> Why does using the marp theme and various styles have no effect in VSCode?

Since we can't know how you use the theme and various styles, we can't give you a definitive answer. The following tips may help you:

- Is the theme CSS located within the workspace that is opening in VS Code?
- Does theme CSS have named by [`@theme` metadata comment](https://marpit.marp.app/theme-css?id=metadata)?
- Is the theme recognized by Marp for VS Code? If recognized, Marp will be supposed to suggest the your theme name in auto-complete of `theme` directive.
- Haven't any syntax errors in CSS? You can validate at https://jigsaw.w3.org/css-validator/.

> And why is the real-time rendering not in the form of PPT but in the form of PDF?

I do not understand what you mean by that question. The realtime preview always use HTML format, neither PPT and PDF.
