### ISSUE TITLE
Marp-vscode Preview Not Working in Latest VSCode Version

### ISSUE THREAD

**Issue by lhrkkk** [marp-team/marp-vscode#459]
### Version of Marp Tool

marp-vscode v2.8.0 - 2023-10-28

### Operating System

macOS

### Environment

- Marp-vscode version: 2.8.0 (2023-10-28)
- Visual Studio Code version: 1.91.0 (Universal)
- OS: macOS 14.5 (23F79)
- Hardware: MacBook Air 15-inch, M2, 2023

### How to reproduce

* Open Visual Studio Code.
* Ensure the Marp-vscode extension is installed and enabled.
* Open a markdown file with Marp slide syntax and ensure `marp: true` is specified.
* Attempt to open the preview using the Marp-vscode extension.
* Notice that the preview renders as regular markdown instead of Marp slides.

### Expected behavior

The preview should render the markdown file as Marp slides, displaying the slide content as intended.

### Actual behavior

The preview renders the markdown file as regular markdown, not displaying the Marp slides correctly.

### Additional information

<img width="1476" alt="iShot_2024-07-15_01 39 29" src="https://github.com/user-attachments/assets/5e3054c9-d799-49ea-ba20-e2ff84ea1e17">

**Comment by yhatt** [comment]
This screenshot shows that the Markdown preview is provided from [Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) extension. Marp for VS code extension is designed for extending [VS Code built-in Markdown preview](https://code.visualstudio.com/Docs/languages/markdown#_markdown-preview), so that is not a bug. Marp preview does not available when opening the preview in any other Markdown preview extensions.

Simply disable Markdown Preview Enhanced extension, or try to open the Markdown preview provided from VS Code, not from other Markdown extensions.
Reference: https://github.com/orgs/marp-team/discussions/423#discussioncomment-5376585

**Comment by lhrkkk** [comment]
Thank you! That solved my problem!

**Comment by sebs** [comment]
vscode 1.99.3 and latest extension is not showing me a blue marp button, no matter what I do. I deinstalled all the extensions.  Any way to debug this error?

**Comment by yhatt** [comment]
Create [a new discussion](https://github.com/orgs/marp-team/discussions) or issue instead of taking over closed/resolved issue. Thanks.
