### ISSUE TITLE
Fragmented list doesn't work in PowerPoint export

### ISSUE THREAD

**Issue by reparke** [marp-team/marp-vscode#66]
When I used the Fragmented unordered list and export to PPTX, the "fragmented" / animation part doesn't work--that is, all the items appear at once. The fragmented effect works fine in HTML, but not in PPTX
Markdown example:
```
Title
* item 1
* item 2
```

My system
OS: Windows 10 Pro version 1803 (build 17134.885)
VSCode: 1.37.1
Marp extension: 0.9.0

**Comment by yhatt** [comment]
Essentially it would be a problem from an integrated [Marp CLI](https://github.com/marp-team/marp-cli) rather than Marp for VS Code. We are using Marp CLI internally when exporting.

The exported PowerPoint document consists of pre-rendered slide images, and currently outputting middle images of fragment animation are not supported in Marp CLI.

Transfer the issue from marp-vscode ▶️ marp-cli to be clear our task. 🚚

**Comment by reparke** [comment]
Ah makes sense. I will move the issue to CLI
