### ISSUE TITLE
Marp preview not work

### ISSUE THREAD

**Issue by bioinformatist** [marp-team/marp-vscode#77]
Hi, 
When I try toggle markdown with marp, nothing happend but my header `marp: true` is changed to `marp: false`. The same situation if call it in `Ctrl + Shift + P`.

What's wrong here?

**Comment by yhatt** [comment]
`marp.markdown.toggleMarpPreview` just toggles preview mode for opened preview.

Please follow [VS Code's help](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview) to open Markdown preview. (Press <kbd>Ctrl + Shift + V</kbd>)

**Comment by bioinformatist** [comment]
Fine, it works! Thank you very much!

**Comment by epogrebnyak** [comment]
> `marp.markdown.toggleMarpPreview` just toggles preview mode for opened preview.
> 
> Please follow [VS Code's help](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview) to open Markdown preview. (Press Ctrl + Shift + V)

Should probably be better reflected in VS Code MArp README.md - you install it, but nothing happens, a bit frustrating to need to look for special key combination.

**Comment by yhatt** [comment]
> Should probably be better reflected in VS Code MArp README.md - you install it, but nothing happens, a bit frustrating to need to look for special key combination.

The most of users should not require to know a key combination because VS Code's Markdown preview can open from the toolbar icon. There is next to Marp icon and easy to find.

Actually, <kbd>Ctrl + Shift + V</kbd> may not work if user or an other installed extension (such as [Markdown Preview Enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/)) have changed key mapping in VS Code. A way that may not work in some cases is not suited to describe in README.
