### ISSUE TITLE
How can I use a markdown extension in vscode preview?

### ISSUE THREAD

**Issue by Inujel** [marp-team/marp-vscode#85]
I'm trying to use markdown-it-plantuml. 

I got it to work with marp/cli with a marp.config.js file, but it seems to be ignored when rendering the preview.

**Comment by yhatt** [comment]
Currently Marp Markdown engine cannot extend in marp-vscode. A customized engine is a feature only in Marp CLI.

[Markdown preview extensions for VS Code](https://code.visualstudio.com/docs/languages/markdown#_extending-the-markdown-preview) were supported in super-early version of Marp for VS Code (v0.0.x). But we canceled it because brought some race conditions (#9). I feel it's difficult to restore extensibility by thinking about the effects of extension performance and reproducibility of the preview.

**Comment by Inujel** [comment]
Alright!
