### ISSUE TITLE
equations are not rendered correctly when extension "Markdown All in One" is enabled

### ISSUE THREAD

**Issue by tosaba** [marp-team/marp-vscode#9]
I noticed that equations are not rendered correctly when another extension (Markdown All in One) is active. As this one is quite popular, I thought it's worth to mention it.

Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

**Comment by yhatt** [comment]
Thanks! I think the math rendering of [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown) conflicts with Marp's it.

VSCode has a huge number of extensions and it's difficult to avoid all of the collision, but it is worth working because Markdown All in One is a very popular extension

**Comment by tosaba** [comment]
No of course, there are too many extensions to keep track on all potential conflicts. I also hesitated to comment on this particular one, but I really like this extension because it provides a lot of convenience when creating a markdown document - including marp slides.

**Comment by yhatt** [comment]
Fixed in #11 and a released [v0.0.5](https://github.com/marp-team/marp-vscode/releases/tag/v0.0.5) includes it.
